title: Josh Rutowski # your name (or website title) here
logo: "/images/circle-cropped.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Detective and Statistics Enthuast</b>
  <br><br>
  <b>Data Scientist - Human Capital Research Corporation</b>
  <br><br>
  <b>About Me</b> I am a 2018 graduate of Miami University where I recieved my B.S. in Mathematics. 
  During my time at Miami, I did research in antibiotic resistance utilizing Analytical Chemistry methods. 
  Ever since then, I have been fascinated by the field of data science and how we can use mathematics and statistics to quantify phenomenon.
  <br><br>
  <a href="https://www.linkedin.com/in/josh-rutowski181/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?hl=en&user=EXT0hm0AAAAJ">View My Research Publications</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
